# Generated by meerkly-agent's release workflow — do not edit here.
# Source: https://github.com/meerkly/meerkly-agent/blob/main/packaging/homebrew/meerkly.rb.tmpl
#
# NOTE: nothing below this comment may contain a literal percent-delimited
# placeholder name. The release job greps the rendered file for leftovers to
# catch a missing artifact, so a placeholder mentioned in prose would fail every
# release.
class Meerkly < Formula
  desc "Share this machine's connection as a meerkly proxy exit node"
  homepage "https://meerkly.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.1/meerkly-1.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "16171036891174e2233bb515a53cbb7303fce9f153dd4d59433d9f637a05d02b"
    end
    on_intel do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.1/meerkly-1.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "40df524a01c73a9a25748f6cbc77cf15f0abc41d8933965220f4b98c4e79d9a8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.1/meerkly-1.2.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "570d0c51b5fe234e42dcefc06842ad3dc05d034056e091d8c4e7ec9b33222cb7"
    end
    on_intel do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.1/meerkly-1.2.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3e7d42033f3a789561864a01317ea4eeb239e14f60a7e09a62311228e18ad307"
    end
  end

  def install
    bin.install "meerkly"
  end

  # A per-user LaunchAgent: it runs as whoever ran `brew services start`, which
  # is what keeps the config file in that user's home and out of sudo's way.
  # `sudo brew services` would make it a root LaunchDaemon — don't.
  service do
    run [opt_bin/"meerkly", "run"]
    keep_alive true
    log_path var/"log/meerkly.log"
    error_log_path var/"log/meerkly.log"
    environment_variables MEERKLY_LOG: "info"
  end

  def caveats
    <<~EOS
      One command to set up and start:

        meerkly init

      It asks for your publisher id and starts the service at login.
      Get an id at https://dashboard.meerkly.com
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/meerkly --version")
  end
end
