# Generated by meerkly-agent's release workflow — do not edit here.
# Source: https://github.com/meerkly/meerkly-agent/blob/main/packaging/homebrew/meerkly.rb.tmpl
#
# NOTE: nothing below this comment may contain a literal percent-delimited
# placeholder name. The release job greps the rendered file for leftovers to
# catch a missing artifact, so a placeholder mentioned in prose would fail every
# release.
class Meerkly < Formula
  desc "Share this machine's connection as a meerkly proxy exit node"
  homepage "https://meerkly.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.0/meerkly-1.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "ea4d2c6256c44b57fe815bb9ae8aa3d1a04f709fea804f6543c003312b805a83"
    end
    on_intel do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.0/meerkly-1.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "df899b84dfe8219b350ffce57fe66c3197482f2ebb70af7349fffc7f1c560c78"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.0/meerkly-1.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "830cbb541394d5a09fe8f3b96dc509d3357d86dea1b5fd2743073b1c41439680"
    end
    on_intel do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.2.0/meerkly-1.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "29fec446918cc14e81e7ad742c78ce00979dabb815656107145867ed77704568"
    end
  end

  def install
    bin.install "meerkly"
  end

  # A per-user LaunchAgent: it runs as whoever ran `brew services start`, which
  # is what keeps the config file in that user's home and out of sudo's way.
  # `sudo brew services` would make it a root LaunchDaemon — don't.
  service do
    run [opt_bin/"meerkly", "run"]
    keep_alive true
    log_path var/"log/meerkly.log"
    error_log_path var/"log/meerkly.log"
    environment_variables MEERKLY_LOG: "info"
  end

  def caveats
    <<~EOS
      One command to set up and start:

        meerkly init

      It asks for your publisher id and starts the service at login.
      Get an id at https://dashboard.meerkly.com
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/meerkly --version")
  end
end
