# Generated by meerkly-agent's release workflow — do not edit here.
# Source: https://github.com/meerkly/meerkly-agent/blob/main/packaging/homebrew/meerkly.rb.tmpl
#
# NOTE: nothing below this comment may contain a literal percent-delimited
# placeholder name. The release job greps the rendered file for leftovers to
# catch a missing artifact, so a placeholder mentioned in prose would fail every
# release.
class Meerkly < Formula
  desc "Share this machine's connection as a meerkly proxy exit node"
  homepage "https://meerkly.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.3.0/meerkly-1.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "bb73d9a6e71f1ecae146816314097616a36688b5d74a97007b83d842c8babd59"
    end
    on_intel do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.3.0/meerkly-1.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "1c65277d3a02ecbaa836e33a39b635d9a6464dfc5f686263140e977c74eb7b27"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.3.0/meerkly-1.3.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5db30f7b2aa46df6db3723fb7ed06f20189de9fe9f08c2e70fcabe6f20c1d4ab"
    end
    on_intel do
      url "https://github.com/meerkly/meerkly-agent/releases/download/v1.3.0/meerkly-1.3.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "7285beb66d27246156bfb5f668a957eab3767863150588a85bfe8dd4ccaf0f11"
    end
  end

  def install
    bin.install "meerkly"
  end

  # A per-user LaunchAgent: it runs as whoever ran `brew services start`, which
  # is what keeps the config file in that user's home and out of sudo's way.
  # `sudo brew services` would make it a root LaunchDaemon — don't.
  service do
    run [opt_bin/"meerkly", "run"]
    keep_alive true
    log_path var/"log/meerkly.log"
    error_log_path var/"log/meerkly.log"
    environment_variables MEERKLY_LOG: "info"
  end

  def caveats
    <<~EOS
      One command to set up and start:

        meerkly init

      It asks for your publisher id and starts the service at login.
      Get an id at https://dashboard.meerkly.com
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/meerkly --version")
  end
end
